In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.axes as ax

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('seed.csv')
data.head()

Area  Perimeter  Compactness  Length of kernel  Width of kernel  \
0  15.26      14.84       0.8710             5.763            3.312   
1  14.88      14.57       0.8811             5.554            3.333   
2  14.29      14.09       0.9050             5.291            3.337   
3  13.84      13.94       0.8955             5.324            3.379   
4  16.14      14.99       0.9034             5.658            3.562   

   Asymmetry coefficient  Length of kernel groove  kernel Unnamed: 8  \
0                  2.221                    5.220       1        NaN   
1                  1.018                    4.956       1        NaN   
2                  2.699                    4.825       1        NaN   
3                  2.259                    4.805       1        NaN   
4                  1.355                    5.175       1        NaN   

  Unnamed: 9  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Area                     210 non-null    float64
 1   Perimeter                210 non-null    float64
 2   Compactness              210 non-null    float64
 3   Length of kernel         210 non-null    float64
 4   Width of kernel          210 non-null    float64
 5   Asymmetry coefficient    210 non-null    float64
 6   Length of kernel groove  210 non-null    float64
 7   kernel                   210 non-null    int64  
 8   Unnamed: 8               2 non-null      object 
 9   Unnamed: 9               1 non-null      object 
dtypes: float64(7), int64(1), object(2)
memory usage: 16.5+ KB


In [7]:
data = data.dropna(axis=1)
data

Area  Perimeter  Compactness  Length of kernel  Width of kernel  \
0    15.26      14.84       0.8710             5.763            3.312   
1    14.88      14.57       0.8811             5.554            3.333   
2    14.29      14.09       0.9050             5.291            3.337   
3    13.84      13.94       0.8955             5.324            3.379   
4    16.14      14.99       0.9034             5.658            3.562   
..     ...        ...          ...               ...              ...   
205  12.19      13.20       0.8783             5.137            2.981   
206  11.23      12.88       0.8511             5.140            2.795   
207  13.20      13.66       0.8883             5.236            3.232   
208  11.84      13.21       0.8521             5.175            2.836   
209  12.30      13.34       0.8684             5.243            2.974   

     Asymmetry coefficient  Length of kernel groove  kernel  
0                    2.221                    5.220       1  
1                    1.018                    4.956       1  
2                    2.699                    4.825       1  
3                    2.259                    4.805       1  
4                    1.355                    5.175       1  
..                     ...                      ...     ...  
205                  3.631                    4.870       3  
206                  4.325                    5.003       3  
207                  8.315                    5.056       3  
208                  3.598                    5.044       3  
209                  5.637                    5.063       3  

[210 rows x 8 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Area                     210 non-null    float64
 1   Perimeter                210 non-null    float64
 2   Compactness              210 non-null    float64
 3   Length of kernel         210 non-null    float64
 4   Width of kernel          210 non-null    float64
 5   Asymmetry coefficient    210 non-null    float64
 6   Length of kernel groove  210 non-null    float64
 7   kernel                   210 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 13.2 KB


In [10]:
#train input data
x = data.drop(data.columns[7], axis=1)
x

Area  Perimeter  Compactness  Length of kernel  Width of kernel  \
0    15.26      14.84       0.8710             5.763            3.312   
1    14.88      14.57       0.8811             5.554            3.333   
2    14.29      14.09       0.9050             5.291            3.337   
3    13.84      13.94       0.8955             5.324            3.379   
4    16.14      14.99       0.9034             5.658            3.562   
..     ...        ...          ...               ...              ...   
205  12.19      13.20       0.8783             5.137            2.981   
206  11.23      12.88       0.8511             5.140            2.795   
207  13.20      13.66       0.8883             5.236            3.232   
208  11.84      13.21       0.8521             5.175            2.836   
209  12.30      13.34       0.8684             5.243            2.974   

     Asymmetry coefficient  Length of kernel groove  
0                    2.221                    5.220  
1                    1.018                    4.956  
2                    2.699                    4.825  
3                    2.259                    4.805  
4                    1.355                    5.175  
..                     ...                      ...  
205                  3.631                    4.870  
206                  4.325                    5.003  
207                  8.315                    5.056  
208                  3.598                    5.044  
209                  5.637                    5.063  

[210 rows x 7 columns]

In [33]:
#train output
y = data['kernel']

y.value_counts()

1    70
2    70
3    70
Name: kernel, dtype: int64

In [34]:
y.unique()

array([1, 2, 3], dtype=int64)

In [17]:
#spliting data
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.20, random_state=0)

In [35]:
xtrain[:10]

array([[ 1.39839588,  1.40691641,  0.54076511,  1.36238574,  1.32859941,
        -0.21222347,  1.48279154],
       [-0.53336705, -0.48148169, -0.44935973, -0.21168047, -0.50286234,
         2.23767528,  0.05269791],
       [ 0.43423001,  0.3180417 ,  1.48046692,  0.04880856,  0.81031185,
        -1.55709562, -0.48257725],
       [ 0.66755129,  0.71399614,  0.34365692,  0.84808688,  0.60621934,
         0.21268398,  0.86268032],
       [ 0.85283583,  0.90435885,  0.33907301,  1.13306633,  0.84253698,
        -0.1066647 ,  1.12526814],
       [ 0.0808169 , -0.02461118,  1.26043918, -0.12707719,  0.54176907,
        -0.3725659 , -0.47247772],
       [-0.567679  , -0.55762677, -0.14223768, -0.53673516, -0.51091862,
         0.31490228, -0.65830909],
       [ 1.7380842 ,  1.78764183,  0.18780394,  2.31305939,  1.35008283,
        -0.28972231,  2.29479386],
       [-0.6363029 , -0.61854284, -0.32101022, -0.53673516, -0.62907744,
        -0.208883  , -1.18954444],
       [ 1.06900113,  0.9805

In [36]:
ytrain[:10]

104    2
141    3
4      1
74     2
136    2
44     1
63     1
108    2
26     1
101    2
Name: kernel, dtype: int64

In [23]:
xtest.shape

(42, 7)

In [24]:
ytrain.shape

(168,)

In [37]:
#scaling the data
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.fit_transform(xtest)


In [27]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
logistic.fit(xtrain,ytrain)

LogisticRegression()

In [28]:
prediction_values= logistic.predict(xtest)
prediction_values

array([1, 2, 1, 1, 3, 2, 2, 2, 2, 3, 1, 3, 1, 3, 2, 2, 3, 1, 1, 1, 3, 1,
       1, 1, 2, 2, 2, 1, 3, 3, 2, 3, 2, 2, 3, 3, 3, 2, 1, 1, 3, 1],
      dtype=int64)

In [30]:
confusion_matrix(prediction_values, ytest)

array([[13,  2,  0],
       [ 0, 14,  0],
       [ 0,  0, 13]], dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest, prediction_values)

0.9523809523809523